### ISSUE TITLE
Fields branch backwards compatibility

### ISSUE THREAD

**Issue by flauted** [flauted/OpenNMT-py#6]
fields breaks backwards compatibility as pointed out on https://github.com/OpenNMT/OpenNMT-py/pull/1196 .

Steps to reproduce:
```
git checkout master
rm -rf /tmp/q*pt
python preprocess.py -train_src /tmp/src-val.txt -train_tgt /tmp/tgt-val.txt -valid_src /tmp/src-val.txt -valid_tgt /tmp/tgt-val.txt -save_data /tmp/q -src_vocab_size 1000 -tgt_vocab_size 1000
python train.py -data /tmp/q -rnn_size 2 -batch_size 10 -word_vec_size 5 -report_every 5 -rnn_size 10 -train_steps 10 -save_model /tmp/dummy-model -save_checkpoint_steps 10
git checkout fields
python translate.py -model /tmp/dummy-model_step_10.pt -src data//morph/src.valid -verbose -batch_size 10  -beam_size 10  -tgt data/morph/tgt.valid -out /tmp/trans
Traceback (most recent call last):
  File "translate.py", line 35, in <module>
    main(opt)
  File "translate.py", line 14, in main
    translator = build_translator(opt, report_score=True)
  File "/home/dylan/code/OpenNMT-py/onmt/translate/translator.py", line 32, in build_translator
    fields, model, model_opt = load_test_model(opt, dummy_opt.__dict__)
  File "/home/dylan/code/OpenNMT-py/onmt/model_builder.py", line 150, in load_test_model
    map_location=lambda storage, loc: storage)
  File "/home/dylan/miniconda3/envs/opennmt27/lib/python2.7/site-packages/torch/serialization.py", line 367, in load
    return _load(f, map_location, pickle_module)
  File "/home/dylan/miniconda3/envs/opennmt27/lib/python2.7/site-packages/torch/serialization.py", line 538, in _load
    result = unpickler.load()
AttributeError: 'module' object has no attribute '_feature_tokenize'
```

**Comment by flauted** [comment]
The exact issue is fixed, but there may be related ones from moving ``make_img`` and removing ``make_audio`` and creating ``AudioSeqField``.

**Comment by flauted** [comment]
```
echo -n "[+] Doing im2text {preprocess w/sharding + train} test..."
git checkout master
rm -rf /tmp/im2text/q*pt
rm -rf /tmp/dummy_model_im*.pt
python preprocess.py -data_type img \
	             -src_dir /tmp/im2text/images \
		     -train_src /tmp/im2text/src-val-head.txt \
		     -train_tgt /tmp/im2text/tgt-val-head.txt \
		     -valid_src /tmp/im2text/src-val-head.txt \
		     -valid_tgt /tmp/im2text/tgt-val-head.txt \
                     -shard_size 5 \
		     -save_data /tmp/im2text/q
python train.py -model_type img \
	        -data /tmp/im2text/q -rnn_size 2 -batch_size 10 \
		-word_vec_size 5 -report_every 5 -rnn_size 10 -train_steps 10 \
                -save_checkpoint_steps 10 -save_model /tmp/dummy_model_im
git checkout fields
python translate.py -data_type img \
	            -src_dir /tmp/im2text/images \
		    -model /tmp/dummy_model_im_step_10.pt \
		    -src /tmp/im2text/src-val-head.txt \
		    -tgt /tmp/im2text/tgt-val-head.txt \
		    -verbose -out /tmp/im2text/trans
Traceback (most recent call last):
  File "translate.py", line 35, in <module>
    main(opt)
  File "translate.py", line 14, in main
    translator = build_translator(opt, report_score=True)
  File "/home/dylan/code/OpenNMT-py/onmt/translate/translator.py", line 32, in build_translator
    fields, model, model_opt = load_test_model(opt, dummy_opt.__dict__)
  File "/home/dylan/code/OpenNMT-py/onmt/model_builder.py", line 150, in load_test_model
    map_location=lambda storage, loc: storage)
  File "/home/dylan/miniconda3/envs/opennmt27/lib/python2.7/site-packages/torch/serialization.py", line 367, in load
    return _load(f, map_location, pickle_module)
  File "/home/dylan/miniconda3/envs/opennmt27/lib/python2.7/site-packages/torch/serialization.py", line 538, in _load
    result = unpickler.load()
AttributeError: 'module' object has no attribute 'make_img'
```

**Comment by flauted** [comment]
```
echo -n "[+] Doing speech2text {preprocess + train} test..."
rm -rf /tmp/speech/q*pt
rm -rf /tmp/dummy_model_audio*.pt
git checkout master
python preprocess.py -data_type audio \
	             -src_dir /tmp/speech/an4_dataset \
		     -train_src /tmp/speech/src-val-head.txt \
		     -train_tgt /tmp/speech/tgt-val-head.txt \
		     -valid_src /tmp/speech/src-val-head.txt \
		     -valid_tgt /tmp/speech/tgt-val-head.txt \
                     -shard_size 50 \
		     -save_data /tmp/speech/q
python train.py -model_type audio \
	        -data /tmp/speech/q -rnn_size 2 -batch_size 10 \
		-word_vec_size 5 -report_every 5 -rnn_size 10 -train_steps 10 \
                -save_checkpoint_steps 10 -save_model /tmp/dummy_model_audio
git checkout fields
python translate.py -data_type audio \
	            -src_dir /tmp/speech/an4_dataset \
		    -model /tmp/dummy_model_audio_step_10.pt \
		    -src /tmp/speech/src-val-head.txt \
		    -tgt /tmp/speech/tgt-val-head.txt \
		    -verbose -out /tmp/speech/trans
Traceback (most recent call last):
  File "translate.py", line 35, in <module>
    main(opt)
  File "translate.py", line 14, in main
    translator = build_translator(opt, report_score=True)
  File "/home/dylan/code/OpenNMT-py/onmt/translate/translator.py", line 32, in build_translator
    fields, model, model_opt = load_test_model(opt, dummy_opt.__dict__)
  File "/home/dylan/code/OpenNMT-py/onmt/model_builder.py", line 150, in load_test_model
    map_location=lambda storage, loc: storage)
  File "/home/dylan/miniconda3/envs/opennmt27/lib/python2.7/site-packages/torch/serialization.py", line 367, in load
    return _load(f, map_location, pickle_module)
  File "/home/dylan/miniconda3/envs/opennmt27/lib/python2.7/site-packages/torch/serialization.py", line 538, in _load
    result = unpickler.load()
AttributeError: 'module' object has no attribute 'make_audio'
```
